[package]
name = "simple-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true # or strip = "symbols"

[dependencies]
reqwest = { version = "0.12.2", features = ["blocking"] }
